import Footer from '@/components/Footer/Footer';
import './globals.css';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Navbar } from '@/components/Navbar/Navbar';
import ToastProvider from '@/providers/toast-provider';
import { ConfigProvider } from 'antd';
import theme from '@/theme/themeConfig';
import StyledComponentsRegistry from '@/lib/AntdRegistry';
import { MobileNav } from '@/components/Navbar/MobileNav';

const font = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'MayIn3d - 3dPrinters',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <link rel='icon' href='/favicon.ico' sizes='any' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'
        />
        {/* <link
          rel='stylesheet'
          type='text/css'
          href='https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css'
        />
        <link
          rel='stylesheet'
          type='text/css'
          href='https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css'
        /> */}
        <ConfigProvider theme={theme}>
          <ToastProvider />
          <div className='md:block hidden'>
            <Navbar />
          </div>
          <div className='md:hidden block'>
            <MobileNav />
          </div>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          <Footer />
        </ConfigProvider>
      </body>
    </html>
  );
}
